_target_: mimic_retargeter_lab.metrics.ReferencePoseMetric
config:
  display_name: "Pinch Grasps"
  reference_type: linear
  joint_space_mapping: ${joint_angle_retargeter.config.joint_mapping}

  vector_diffs:
    - name: thumb_to_index_tip
      src: THUMB_TIP
      tgt: INDEX_TIP
    - name: thumb_to_middle_tip
      src: THUMB_TIP
      tgt: MIDDLE_TIP
    - name: thumb_to_ring_tip
      src: THUMB_TIP
      tgt: RING_TIP
    - name: thumb_to_little_tip
      src: THUMB_TIP
      tgt: PINKY_TIP

data_source_cfg:
  _target_: mimic_retargeter_lab.data_sources.HandDatasetReader
  data_path: "./dataset/pinch_grasps"
  dataset: "pinch_grasps_test"
