_target_: mimic_retargeter_lab.metrics.FlatnessMetric
config:
  display_name: "Flatness"

  task_space_mapping:
    - landmark: THUMB_TIP
    - landmark: INDEX_TIP
    - landmark: MIDDLE_TIP

data_source_cfg: ${dataset.data_source_cfg}
