_target_: dexworld.metrics.KeyvectorMatchingMetric
config:
  display_name: "Keyvector Matching"
  joint_space_mapping: ${joint_angle_retargeter.config.joint_mapping}

  vector_diffs:
    - name: thumb_to_index_tip
      src: THUMB_TIP
      tgt: INDEX_TIP
    - name: thumb_to_middle_tip
      src: THUMB_TIP
      tgt: MIDDLE_TIP
    - name: thumb_to_ring_tip
      src: THUMB_TIP
      tgt: RING_TIP

data_source_cfg: ${dataset.data_source_cfg}
