"""Compare GeoRT's trained FK MLP against the MJX FK ground truth.

Both should produce nearly-identical fingertip positions for any random
qpos within joint limits — the MLP was trained on data generated by the
MJX-backed `MjcfHandKinematicModel.keypoint_from_qpos`. RMS divergence in
the sub-millimeter range = the MLP fit converged. Anything larger
indicates undertraining or a wiring bug.

Usage (from repo root):
    JAX_PLATFORMS=cpu python scripts/compare_fk_models.py \\
        --hand mimic_p050_hand --chirality right --tracker manus \\
        --n-samples 2000
"""

import mimic_retargeter_lab  # noqa: F401  pins JAX_PLATFORMS

import argparse
from pathlib import Path

import jax.numpy as jnp
import numpy as np
import torch
from omegaconf import OmegaConf

from mimic_retargeter_lab.hand_models import create_robot_hand
from mimic_retargeter_lab.types import Chirality, HandLandmark, RobotHandType


REPO_ROOT = Path(__file__).resolve().parent.parent
GEORT_FK_CKPT_DIR = REPO_ROOT / "third_party" / "geort" / "checkpoint"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--hand", default="mimic_p050_hand")
    p.add_argument("--chirality", default="right", choices=["left", "right"])
    p.add_argument("--tracker", default="manus")
    p.add_argument("--n-samples", type=int, default=2000)
    p.add_argument("--seed", type=int, default=0)
    return p.parse_args()


def main() -> None:
    args = parse_args()

    # Build the robot.
    hand_path = REPO_ROOT / "assets" / "mjcf" / args.hand
    to_model = create_robot_hand(
        RobotHandType(args.hand), hand_path, Chirality(args.chirality)
    )

    # Read the same per-hand yaml the trainer used.
    yaml_path = (
        REPO_ROOT
        / "config"
        / "retargeter"
        / "geort"
        / f"human_hand_to_{args.hand}.yaml"
    )
    cfg = OmegaConf.to_container(OmegaConf.load(yaml_path), resolve=True)
    fingertips = cfg["training"]["fingertips"]

    # Reconstruct the trainer's `keypoint_joints` layout: per-finger lists
    # of indices into the 16-dim user qpos vector (joint_order).
    joint_order = [
        to_model._joint_name_from_actuated_name(n)
        for n in to_model.get_actuated_joint_names()
    ]
    keypoint_joints = [[joint_order.index(j) for j in f["joint"]] for f in fingertips]
    finger_names = [f["name"] for f in fingertips]
    finger_link_names = [
        to_model._landmark_config[HandLandmark(str(f["landmark"]).lower())].name
        for f in fingertips
    ]

    # Joint limits ordered by joint_order for sampling + normalization.
    actuated_limits = to_model.get_actuated_joint_limits()
    qpos_to_actuated = {
        to_model._joint_name_from_actuated_name(a): a
        for a in to_model.get_actuated_joint_names()
    }
    lower = np.array(
        [actuated_limits[qpos_to_actuated[n]][0] for n in joint_order], dtype=np.float32
    )
    upper = np.array(
        [actuated_limits[qpos_to_actuated[n]][1] for n in joint_order], dtype=np.float32
    )

    # Load the trained FK MLP.
    cache_name = f"{args.hand}_{args.chirality}_{args.tracker}_mjcf"
    fk_ckpt_path = GEORT_FK_CKPT_DIR / f"fk_model_{cache_name}.pth"
    if not fk_ckpt_path.exists():
        raise FileNotFoundError(
            f"FK MLP checkpoint not found: {fk_ckpt_path}\n"
            f"Train one first with `python -m mimic_retargeter_lab.retargeting.online.geort.train ...`"
        )

    from geort.formatter import HandFormatter
    from geort.model import FKModel

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is required: GeoRT's FKModel hardcodes .cuda(). "
            "Run on a host with a working torch CUDA stack."
        )
    fk_model = FKModel(keypoint_joints=keypoint_joints).cuda()
    fk_model.load_state_dict(torch.load(str(fk_ckpt_path)))
    fk_model.eval()
    qpos_normalizer = HandFormatter(lower, upper)
    print(f"Loaded FK MLP: {fk_ckpt_path}")

    # Sample random qpos within MJCF joint limits.
    rng = np.random.default_rng(args.seed)
    qpos = rng.uniform(lower, upper, size=(args.n_samples, len(joint_order))).astype(
        np.float32
    )

    # Predicted (FK MLP).
    with torch.no_grad():
        q_t = torch.from_numpy(qpos).float().cuda()
        q_norm = qpos_normalizer.normalize_torch(q_t)
        predicted = fk_model(q_norm).cpu().numpy()  # (N, F, 3)

    # Ground truth (MJX FK). joint_order is unprefixed; the actuated joints
    # are in the same order, so qpos lines up with the ctrl vector.
    ctrl_jax = jnp.asarray(qpos)
    fk_dict = to_model.mjx_fk_body_positions(ctrl_jax, joint_space="ctrl")
    ground_truth = np.stack(
        [np.asarray(fk_dict[name]) for name in finger_link_names], axis=1
    )  # (N, F, 3)

    # Per-finger error.
    diff = predicted - ground_truth  # (N, F, 3)
    per_finger_l2 = np.linalg.norm(diff, axis=-1)  # (N, F)
    rmse_mm = 1000.0 * np.sqrt(np.mean(per_finger_l2**2, axis=0))
    mean_mm = 1000.0 * np.mean(per_finger_l2, axis=0)
    p95_mm = 1000.0 * np.quantile(per_finger_l2, 0.95, axis=0)
    max_mm = 1000.0 * np.max(per_finger_l2, axis=0)

    print(f"\nFK MLP vs MJX FK on {args.n_samples} random qpos samples:")
    print(f"  hand={args.hand} chirality={args.chirality} tracker={args.tracker}\n")
    header = f"{'finger':<10}{'mean (mm)':>12}{'rmse (mm)':>12}{'p95 (mm)':>12}{'max (mm)':>12}"
    print(header)
    print("-" * len(header))
    for i, name in enumerate(finger_names):
        print(
            f"{name:<10}{mean_mm[i]:>12.3f}{rmse_mm[i]:>12.3f}"
            f"{p95_mm[i]:>12.3f}{max_mm[i]:>12.3f}"
        )

    overall_rmse = 1000.0 * np.sqrt(np.mean(per_finger_l2**2))
    overall_mean = 1000.0 * np.mean(per_finger_l2)
    overall_p95 = 1000.0 * np.quantile(per_finger_l2.flatten(), 0.95)
    overall_max = 1000.0 * np.max(per_finger_l2)
    print("-" * len(header))
    print(
        f"{'overall':<10}{overall_mean:>12.3f}{overall_rmse:>12.3f}"
        f"{overall_p95:>12.3f}{overall_max:>12.3f}"
    )


if __name__ == "__main__":
    main()
